/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync User
         * @description Upsert user from Clerk JWT token.
         *     Called by frontend after successful Clerk login.
         */
        post: operations["sync_user_api_v1_auth_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Profile
         * @description Get current user profile using JWT from Authorization header.
         */
        get: operations["get_current_user_profile_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_v1_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Document
         * @description Upload a study document (PDF, image, text) for processing.
         *
         *     Creates a Document record, a Job record, and dispatches an ARQ job.
         *     Returns IDs for polling.
         */
        post: operations["upload_document_api_v1_documents_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/summaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Summaries */
        get: operations["list_summaries_api_v1_summaries_get"];
        put?: never;
        /**
         * Create Summary
         * @description Request a summary for a given document.
         *
         *     Creates a pending Summary record and a Job, then triggers the summary chain.
         *     Returns the summary ID and job ID for polling.
         */
        post: operations["create_summary_api_v1_summaries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/summaries/{summary_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Summary */
        get: operations["get_summary_api_v1_summaries__summary_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quizzes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Quizzes */
        get: operations["list_quizzes_api_v1_quizzes_get"];
        put?: never;
        /**
         * Create Quiz
         * @description Request a quiz for a given document.
         *
         *     Delegates to the quiz service layer which handles validation,
         *     record creation, and ARQ job enqueueing. Returns a job_id for SSE streaming.
         */
        post: operations["create_quiz_api_v1_quizzes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quizzes/{quiz_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quiz */
        get: operations["get_quiz_api_v1_quizzes__quiz_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quizzes/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Attempt
         * @description Submit a quiz attempt and get results.
         *
         *     Delegates to the quiz service layer which handles validation,
         *     score calculation, topic performance updates, and weak topic detection.
         */
        post: operations["submit_attempt_api_v1_quizzes_attempts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practice/lesson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Lesson
         * @description Generate a concise mini-lesson for the given topics.
         *
         *     Retrieves relevant user-scoped chunks and generates a 2-paragraph explanation.
         */
        post: operations["generate_lesson_api_v1_practice_lesson_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Practice
         * @description Request targeted practice drills for weak topics.
         *
         *     Delegates to the practice service layer which handles chain invocation
         *     and session record creation.
         */
        post: operations["create_practice_api_v1_practice_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practice/weak-areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Weak Areas */
        get: operations["get_weak_areas_api_v1_practice_weak_areas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practice/{practice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Practice Session */
        get: operations["get_practice_session_api_v1_practice__practice_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Ask a question about uploaded documents.
         *
         *     Uses grounded chat chain to retrieve relevant chunks and generate answer.
         */
        post: operations["chat_api_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Job Progress
         * @description Stream Server-Sent Events (SSE) for job status updates.
         *     Frontend polls this endpoint to show real‑time progress.
         */
        get: operations["stream_job_progress_api_v1_jobs__job_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_document_api_v1_documents_upload_post */
        Body_upload_document_api_v1_documents_upload_post: {
            /** File */
            file: string;
        };
        /**
         * ChatMessage
         * @description Individual message in chat history.
         */
        ChatMessage: {
            /** Role */
            role: string;
            /** Content */
            content: string;
        };
        /**
         * ChatRequest
         * @description Request body for chat endpoint.
         */
        ChatRequest: {
            /** Document Id */
            document_id?: string | null;
            /** Question */
            question: string;
            /**
             * Messages
             * @default []
             */
            messages: components["schemas"]["ChatMessage"][];
        };
        /**
         * ChatResponse
         * @description Response from chat endpoint.
         */
        ChatResponse: {
            /** Answer */
            answer: string;
            /** Citations */
            citations: {
                [key: string]: unknown;
            }[];
            /** Relevant Chunks */
            relevant_chunks: string[];
        };
        /**
         * CreatePracticeRequest
         * @description Request body for creating a practice session.
         */
        CreatePracticeRequest: {
            /** Weak Topics */
            weak_topics: string[];
            /**
             * Drill Count
             * @default 5
             */
            drill_count: number;
        };
        /**
         * CreatePracticeResponse
         * @description Response after creating a practice session.
         */
        CreatePracticeResponse: {
            /** Practice Id */
            practice_id: string;
            /** Drills */
            drills: {
                [key: string]: unknown;
            }[];
            /** Message */
            message: string;
        };
        /**
         * CreateQuizRequest
         * @description Request body for creating a quiz.
         */
        CreateQuizRequest: {
            /** Document Id */
            document_id: string;
            /**
             * Question Count
             * @default 5
             */
            question_count: number;
            /**
             * Auto Mode
             * @default true
             */
            auto_mode: boolean;
        };
        /**
         * CreateQuizResponse
         * @description Response after creating a quiz job.
         */
        CreateQuizResponse: {
            /** Job Id */
            job_id: string;
            /** Quiz Id */
            quiz_id: string;
            /** Message */
            message: string;
        };
        /**
         * CreateSummaryRequest
         * @description Request body for creating a summary.
         */
        CreateSummaryRequest: {
            /** Document Id */
            document_id: string;
            override_preferences?: components["schemas"]["OverridePreferences"] | null;
        };
        /** CreateSummaryResponse */
        CreateSummaryResponse: {
            /** Summary Id */
            summary_id: string;
            /** Job Id */
            job_id: string;
            /** Message */
            message: string;
        };
        /** DocumentListItem */
        DocumentListItem: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Status */
            status: string;
            /** Created At */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LessonRequest
         * @description Request body for generating a mini-lesson.
         */
        LessonRequest: {
            /** Topics */
            topics: string[];
        };
        /**
         * LessonResponse
         * @description Response containing a generated mini-lesson.
         */
        LessonResponse: {
            /** Lesson */
            lesson: string;
            /** Chunks Used */
            chunks_used: number;
        };
        /** OverridePreferences */
        OverridePreferences: {
            /** Education Level */
            education_level?: string | null;
            /** Output Formats */
            output_formats?: string[] | null;
            /** Explanation Styles */
            explanation_styles?: string[] | null;
            /** Custom Instructions */
            custom_instructions?: string | null;
        };
        /** PracticeDetailResponse */
        PracticeDetailResponse: {
            /** Id */
            id: string;
            /** Weak Topics */
            weak_topics: string[];
            /** Drills */
            drills: {
                [key: string]: unknown;
            }[];
            /** Created At */
            created_at: string;
        };
        /** QuizDetailResponse */
        QuizDetailResponse: {
            /** Id */
            id: string;
            /** Document Id */
            document_id: string;
            /** Title */
            title: string | null;
            /** Questions */
            questions: {
                [key: string]: unknown;
            }[];
            /** Question Types */
            question_types: string[];
            /** Question Count */
            question_count: number;
            /** Auto Mode */
            auto_mode: boolean;
            /** Created At */
            created_at: string;
        };
        /** QuizItemResponse */
        QuizItemResponse: {
            /** Id */
            id: string;
            /** Document Id */
            document_id: string;
            /** Title */
            title: string | null;
            /** Question Count */
            question_count: number;
            /** Question Types */
            question_types: string[];
            /** Created At */
            created_at: string;
        };
        /**
         * SubmitAttemptRequest
         * @description Request body for submitting a quiz attempt.
         */
        SubmitAttemptRequest: {
            /** Quiz Id */
            quiz_id: string;
            /** Answers */
            answers: {
                [key: string]: string;
            };
        };
        /**
         * SubmitAttemptResponse
         * @description Response after submitting an attempt.
         */
        SubmitAttemptResponse: {
            /** Attempt Id */
            attempt_id: string;
            /** Score */
            score: number;
            /** Weak Topics */
            weak_topics: string[];
            /** Message */
            message: string;
        };
        /** SummaryResponse */
        SummaryResponse: {
            /** Id */
            id: string;
            /** Document Id */
            document_id: string;
            /** Title */
            title: string | null;
            /** Content */
            content: string;
            /** Quiz Type Flags */
            quiz_type_flags: unknown;
            /** Created At */
            created_at: string;
        };
        /**
         * SyncRequest
         * @description Request body for auth/sync endpoint.
         */
        SyncRequest: {
            /** Token */
            token: string;
        };
        /**
         * UserResponse
         * @description User profile response.
         */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string | null;
            /** Image */
            image: string | null;
            /** Tier */
            tier: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sync_user_api_v1_auth_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_profile_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_documents_api_v1_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListItem"][];
                };
            };
        };
    };
    upload_document_api_v1_documents_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_documents_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_summaries_api_v1_summaries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"][];
                };
            };
        };
    };
    create_summary_api_v1_summaries_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSummaryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_api_v1_summaries__summary_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                summary_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_quizzes_api_v1_quizzes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizItemResponse"][];
                };
            };
        };
    };
    create_quiz_api_v1_quizzes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQuizRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateQuizResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quiz_api_v1_quizzes__quiz_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quiz_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_attempt_api_v1_quizzes_attempts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAttemptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitAttemptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_lesson_api_v1_practice_lesson_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_practice_api_v1_practice_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePracticeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatePracticeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_weak_areas_api_v1_practice_weak_areas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_practice_session_api_v1_practice__practice_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                practice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_v1_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_job_progress_api_v1_jobs__job_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
